### ISSUE TITLE
React router urls don't work when refreshing or writing manually

### ISSUE THREAD

**Issue by yoursanjib** [neo7official/webpack4RealZeroConfig#2]
Links are working fine if I clicking in a link, but when I refresh my application it does not work.

**Comment by neo7official** [comment]
Hello yoursanjib, thanks for pointing that out. That was happening as it was using webpack dev server and so it needs to know if it can use javascript history object. So, I have added  historyApiFallback: true. Feel free to reopen the issue if you need to.
